unit module LLattice::GeneratedProviderAbi;

use NativeCall;
need Vinary::Tree::Interop;

# Code generated by scripts/generate-raku-provider-abi.py from
# bindings/raku/provider-api.json; DO NOT EDIT.
our constant PROVIDER-ABI-VERSION is export = 1;
our constant PROVIDER-API-REVISION is export = 1;
our constant PROVIDER-REQUIRED-CAPABILITIES is export = 15;
our constant PROVIDER-CALLING-CONVENTION is export = 'cdecl';
our constant PROVIDER-CAPABILITY-CONFIGURE-ONCE is export = 1;
our constant PROVIDER-CAPABILITY-HOST-CONTEXT is export = 2;
our constant PROVIDER-CAPABILITY-INDEXED-HOST-CONTEXT is export = 4;
our constant PROVIDER-CAPABILITY-BATCH is export = 8;

our constant TYPE-RAKU-REPRESENTATIONS is export = Map.new(
    'VtInterfaceId' => 'Vinary::Tree::Interop::InterfaceId',
    'VtResource' => 'Vinary::Tree::Interop::RawResource',
);

our constant TYPE-OWNERSHIP is export = Map.new(
    'VtInterfaceId' => 'borrowed-or-value-as-declared',
    'VtResource' => 'reference-counted-retain',
);

our constant C-SIGNATURES is export = Map.new(
    'llattice_raku_provider_abi_version' => 'LLATTICE_RAKU_API uint32_t llattice_raku_provider_abi_version(void);',
    'llattice_raku_provider_api_revision' => 'LLATTICE_RAKU_API uint32_t llattice_raku_provider_api_revision(void);',
    'llattice_raku_provider_capabilities' => 'LLATTICE_RAKU_API uint64_t llattice_raku_provider_capabilities(void);',
    'llattice_raku_provider_sizeof_interface_id' => 'LLATTICE_RAKU_API size_t llattice_raku_provider_sizeof_interface_id(void);',
    'llattice_raku_provider_sizeof_resource' => 'LLATTICE_RAKU_API size_t llattice_raku_provider_sizeof_resource(void);',
    'llattice_raku_provider_configure' => 'LLATTICE_RAKU_API VtStatus llattice_raku_provider_configure(LlatticeRakuDrop drop, LlatticeRakuBinary join, LlatticeRakuBinary meet, LlatticeRakuEqual equal, LlatticeRakuBytes stable_bytes, LlatticeRakuBytes diagnostic, LlatticeRakuMany join_many, LlatticeRakuMany meet_many);',
    'llattice_raku_provider_create' => 'LLATTICE_RAKU_API VtStatus llattice_raku_provider_create(const VtInterfaceId* domain_id, uint64_t flags, void* host_context, VtResource* out_resource);',
    'llattice_raku_provider_host_context' => 'LLATTICE_RAKU_API VtStatus llattice_raku_provider_host_context(const VtResource* resource, void** out_host_context);',
    'llattice_raku_provider_host_context_at' => 'LLATTICE_RAKU_API VtStatus llattice_raku_provider_host_context_at(const VtResource* resources, size_t index, void** out_host_context);',
);

our constant FUNCTION-SINCE-API-REVISION is export = Map.new(
    'llattice_raku_provider_abi_version' => 1,
    'llattice_raku_provider_api_revision' => 1,
    'llattice_raku_provider_capabilities' => 1,
    'llattice_raku_provider_sizeof_interface_id' => 1,
    'llattice_raku_provider_sizeof_resource' => 1,
    'llattice_raku_provider_configure' => 1,
    'llattice_raku_provider_create' => 1,
    'llattice_raku_provider_host_context' => 1,
    'llattice_raku_provider_host_context_at' => 1,
);

our constant PARAMETER-OWNERSHIP is export = Map.new(
    'LlatticeRakuDrop:host_context' => 'borrowed-final-callback',
    'LlatticeRakuBinary:host_context' => 'borrowed-for-call',
    'LlatticeRakuBinary:other_host_context' => 'borrowed-for-call',
    'LlatticeRakuBinary:other' => 'borrowed-for-call',
    'LlatticeRakuBinary:out_value' => 'owned-retain-on-success',
    'LlatticeRakuEqual:host_context' => 'borrowed-for-call',
    'LlatticeRakuEqual:other_host_context' => 'borrowed-for-call',
    'LlatticeRakuEqual:other' => 'borrowed-for-call',
    'LlatticeRakuEqual:out_equal' => 'borrowed-output-slot',
    'LlatticeRakuBytes:host_context' => 'borrowed-for-call',
    'LlatticeRakuBytes:out_bytes' => 'borrowed-output-buffer',
    'LlatticeRakuBytes:capacity' => 'value',
    'LlatticeRakuBytes:out_written' => 'borrowed-output-slot',
    'LlatticeRakuBytes:out_required' => 'borrowed-output-slot',
    'LlatticeRakuMany:host_context' => 'borrowed-for-call',
    'LlatticeRakuMany:others' => 'borrowed-array-for-call',
    'LlatticeRakuMany:count' => 'value',
    'LlatticeRakuMany:out_value' => 'owned-retain-on-success',
    'llattice_raku_provider_configure:drop' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:join' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:meet' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:equal' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:stable_bytes' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:diagnostic' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:join_many' => 'borrowed-process-lifetime',
    'llattice_raku_provider_configure:meet_many' => 'borrowed-process-lifetime',
    'llattice_raku_provider_create:domain_id' => 'borrowed-for-call',
    'llattice_raku_provider_create:flags' => 'value',
    'llattice_raku_provider_create:host_context' => 'borrowed-until-drop-callback',
    'llattice_raku_provider_create:out_resource' => 'owned-retain-on-success',
    'llattice_raku_provider_host_context:resource' => 'borrowed-for-call',
    'llattice_raku_provider_host_context:out_host_context' => 'borrowed-provider-context',
    'llattice_raku_provider_host_context_at:resources' => 'borrowed-array-for-call',
    'llattice_raku_provider_host_context_at:index' => 'value',
    'llattice_raku_provider_host_context_at:out_host_context' => 'borrowed-provider-context',
);

our constant PARAMETER-NULLABILITY is export = Map.new(
    'LlatticeRakuDrop:host_context' => 'non-null',
    'LlatticeRakuBinary:host_context' => 'non-null',
    'LlatticeRakuBinary:other_host_context' => 'nullable-for-foreign-provider',
    'LlatticeRakuBinary:other' => 'non-null',
    'LlatticeRakuBinary:out_value' => 'non-null',
    'LlatticeRakuEqual:host_context' => 'non-null',
    'LlatticeRakuEqual:other_host_context' => 'nullable-for-foreign-provider',
    'LlatticeRakuEqual:other' => 'non-null',
    'LlatticeRakuEqual:out_equal' => 'non-null',
    'LlatticeRakuBytes:host_context' => 'non-null',
    'LlatticeRakuBytes:out_bytes' => 'nullable-if-capacity-is-zero',
    'LlatticeRakuBytes:capacity' => 'not-applicable',
    'LlatticeRakuBytes:out_written' => 'non-null',
    'LlatticeRakuBytes:out_required' => 'non-null',
    'LlatticeRakuMany:host_context' => 'non-null',
    'LlatticeRakuMany:others' => 'nullable-if-count-is-zero',
    'LlatticeRakuMany:count' => 'not-applicable',
    'LlatticeRakuMany:out_value' => 'non-null',
    'llattice_raku_provider_configure:drop' => 'non-null',
    'llattice_raku_provider_configure:join' => 'non-null',
    'llattice_raku_provider_configure:meet' => 'non-null',
    'llattice_raku_provider_configure:equal' => 'non-null',
    'llattice_raku_provider_configure:stable_bytes' => 'non-null',
    'llattice_raku_provider_configure:diagnostic' => 'non-null',
    'llattice_raku_provider_configure:join_many' => 'non-null',
    'llattice_raku_provider_configure:meet_many' => 'non-null',
    'llattice_raku_provider_create:domain_id' => 'non-null',
    'llattice_raku_provider_create:flags' => 'not-applicable',
    'llattice_raku_provider_create:host_context' => 'non-null',
    'llattice_raku_provider_create:out_resource' => 'non-null',
    'llattice_raku_provider_host_context:resource' => 'non-null',
    'llattice_raku_provider_host_context:out_host_context' => 'non-null',
    'llattice_raku_provider_host_context_at:resources' => 'non-null',
    'llattice_raku_provider_host_context_at:index' => 'not-applicable',
    'llattice_raku_provider_host_context_at:out_host_context' => 'non-null',
);

sub provider-library(--> Str:D) {
    state $library = %*ENV<LLATTICE_RAKU_PROVIDER_LIB>
        // %?RESOURCES<libraries/llattice_raku_provider>.IO.Str;
    $library
}

our sub provider-abi-version(
    --> uint32
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_abi_version')
    is export(:native)
{ * }

our sub provider-api-revision(
    --> uint32
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_api_revision')
    is export(:native)
{ * }

our sub provider-capabilities(
    --> uint64
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_capabilities')
    is export(:native)
{ * }

our sub provider-sizeof-interface-id(
    --> size_t
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_sizeof_interface_id')
    is export(:native)
{ * }

our sub provider-sizeof-resource(
    --> size_t
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_sizeof_resource')
    is export(:native)
{ * }

our sub configure-provider(
    &drop (Pointer),
    &join (Pointer, Pointer, Pointer, Pointer --> int32),
    &meet (Pointer, Pointer, Pointer, Pointer --> int32),
    &equal (Pointer, Pointer, Pointer, Pointer --> int32),
    &stable-bytes (Pointer, Pointer, size_t, Pointer, Pointer --> int32),
    &diagnostic (Pointer, Pointer, size_t, Pointer, Pointer --> int32),
    &join-many (Pointer, Pointer, size_t, Pointer --> int32),
    &meet-many (Pointer, Pointer, size_t, Pointer --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_configure')
    is export(:native)
{ * }

our sub create-provider(
    Vinary::Tree::Interop::InterfaceId,
    uint64,
    Pointer,
    Vinary::Tree::Interop::RawResource,
    --> int32
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_create')
    is export(:native)
{ * }

our sub provider-host-context(
    Vinary::Tree::Interop::RawResource,
    Pointer is rw,
    --> int32
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_host_context')
    is export(:native)
{ * }

our sub provider-host-context-at(
    Pointer,
    size_t,
    Pointer is rw,
    --> int32
)
    is native(&provider-library)
    is symbol('llattice_raku_provider_host_context_at')
    is export(:native)
{ * }

our sub validate-provider-abi(--> Nil) is export(:native) {
    my $abi = provider-abi-version();
    die "llattice Raku provider ABI mismatch: native $abi / "
        ~ "facade {PROVIDER-ABI-VERSION}"
        unless $abi == PROVIDER-ABI-VERSION;
    my $api = provider-api-revision();
    die "llattice Raku provider API revision $api is older than "
        ~ PROVIDER-API-REVISION
        unless $api >= PROVIDER-API-REVISION;
    my $capabilities = provider-capabilities();
    die "llattice Raku provider capabilities are incomplete"
        unless ($capabilities +& PROVIDER-REQUIRED-CAPABILITIES)
            == PROVIDER-REQUIRED-CAPABILITIES;
    die "llattice Raku provider VtInterfaceId layout mismatch"
        unless provider-sizeof-interface-id()
            == nativesizeof(Vinary::Tree::Interop::InterfaceId);
    die "llattice Raku provider VtResource layout mismatch"
        unless provider-sizeof-resource()
            == nativesizeof(Vinary::Tree::Interop::RawResource);
}
