/* Code generated by scripts/generate-raku-provider-abi.py; DO NOT EDIT. */
#ifndef LLATTICE_RAKU_PROVIDER_H
#define LLATTICE_RAKU_PROVIDER_H

#include <stddef.h>
#include <stdint.h>
#include "vinary_tree_interop.h"

#if defined(_WIN32) || defined(__CYGWIN__)
#define LLATTICE_RAKU_API __declspec(dllexport)
#elif defined(__GNUC__) || defined(__clang__)
#define LLATTICE_RAKU_API __attribute__((visibility("default")))
#else
#define LLATTICE_RAKU_API
#endif

#define LLATTICE_RAKU_PROVIDER_ABI_VERSION 1u
#define LLATTICE_RAKU_PROVIDER_API_REVISION 1u
#define LLATTICE_RAKU_PROVIDER_CAPABILITY_CONFIGURE_ONCE UINT64_C(1)
#define LLATTICE_RAKU_PROVIDER_CAPABILITY_HOST_CONTEXT UINT64_C(2)
#define LLATTICE_RAKU_PROVIDER_CAPABILITY_INDEXED_HOST_CONTEXT UINT64_C(4)
#define LLATTICE_RAKU_PROVIDER_CAPABILITY_BATCH UINT64_C(8)
#define LLATTICE_RAKU_PROVIDER_CAPABILITIES \
    (LLATTICE_RAKU_PROVIDER_CAPABILITY_CONFIGURE_ONCE | LLATTICE_RAKU_PROVIDER_CAPABILITY_HOST_CONTEXT | LLATTICE_RAKU_PROVIDER_CAPABILITY_INDEXED_HOST_CONTEXT | LLATTICE_RAKU_PROVIDER_CAPABILITY_BATCH)

#ifdef __cplusplus
extern "C" {
#endif

typedef void (*LlatticeRakuDrop)(
    void* host_context);

typedef VtStatus (*LlatticeRakuBinary)(
    void* host_context,
    void* other_host_context,
    const VtResource* other,
    VtResource* out_value);

typedef VtStatus (*LlatticeRakuEqual)(
    void* host_context,
    void* other_host_context,
    const VtResource* other,
    uint8_t* out_equal);

typedef VtStatus (*LlatticeRakuBytes)(
    void* host_context,
    uint8_t* out_bytes,
    size_t capacity,
    size_t* out_written,
    size_t* out_required);

typedef VtStatus (*LlatticeRakuMany)(
    void* host_context,
    const VtResource* others,
    size_t count,
    VtResource* out_value);

LLATTICE_RAKU_API uint32_t llattice_raku_provider_abi_version(void);

LLATTICE_RAKU_API uint32_t llattice_raku_provider_api_revision(void);

LLATTICE_RAKU_API uint64_t llattice_raku_provider_capabilities(void);

LLATTICE_RAKU_API size_t llattice_raku_provider_sizeof_interface_id(void);

LLATTICE_RAKU_API size_t llattice_raku_provider_sizeof_resource(void);

LLATTICE_RAKU_API VtStatus llattice_raku_provider_configure(
    LlatticeRakuDrop drop,
    LlatticeRakuBinary join,
    LlatticeRakuBinary meet,
    LlatticeRakuEqual equal,
    LlatticeRakuBytes stable_bytes,
    LlatticeRakuBytes diagnostic,
    LlatticeRakuMany join_many,
    LlatticeRakuMany meet_many);

LLATTICE_RAKU_API VtStatus llattice_raku_provider_create(
    const VtInterfaceId* domain_id,
    uint64_t flags,
    void* host_context,
    VtResource* out_resource);

LLATTICE_RAKU_API VtStatus llattice_raku_provider_host_context(
    const VtResource* resource,
    void** out_host_context);

LLATTICE_RAKU_API VtStatus llattice_raku_provider_host_context_at(
    const VtResource* resources,
    size_t index,
    void** out_host_context);

#ifdef __cplusplus
}
#endif

#endif /* LLATTICE_RAKU_PROVIDER_H */
